import Work from '../work_experience'; 
import Card from '../../components/Card';

export default function Experience() {
    const experiences: Work[] = [
      {
        title: "IT Compliance, Audit, and Risk Intern at Martin's Point Health Care",
        date: "May 2025 to Present",
        bullets: [
          'Conduct security reviews on vendors that process sensitive patient information',
          'Contribute to the development of company risk and privacy policies',
          'Update risk management register with new information as needed '
            ],
            link:'',
            linkText: ''
        },
        {
          title: 'Research Assistant at PERC Lab',
          date: 'May 2023 to Present',
          bullets: [
            'Develop a React-based website to teach online privacy and security to children ',
            'Annotate privacy statements generated by LLMs for refinement ',
            'Review and analyze other student projects '],
            link:'',
            linkText: ''
        },
                {
            title: 'Learning Assistant at University of Maine',
            date: 'Jan 2025 to May 2025',
            bullets: [
            'Assist with in-class lectures and assignments for COS 125, an introduction to programming course using Python',
            'Tutor students in Computer Science Help Lab',
            'Conduct exam review sessions',
            'Proctor exams'
            ],
            link:'',
            linkText: ''
        },
        {
            title: 'IT Intern at Kleinschmidt Associates',
            date: 'May 2024 to Aug 2024',
            bullets: [
            'Set up hardware and accounts using Entra ID',
            'Conduct IT orientation for new employees',
            'Handle Help Desk tickets',
            'Monitor over 200 company computers',
            ],
            link:'',
            linkText: ''
        },
        {
          title: 'Instructor at Code Ninjas',
          date: 'May 2023 to July 2023',
          bullets:[
            'Teach children ages 6 - 14 computer science and programming principles ',
            'Manage summer camps for children ages 5 - 8 focused on STEM lessons ',
            'Assist with a summer camp where students create game modifications for Minecraft using Java'
          ],
          link:'',
          linkText: ''
        }

];

return (
  <div>
      <h1 className="text-2xl font-semibold mb-4 text-center">Experience</h1>
      <Card experiences={experiences} />
  </div>
);

}
