import Work from '../work_experience'; 
import Card from '../../components/Card';

export default function Reserach() {
    const experiences: Work[] = [
        {
            title:'Ctrl+Privacy',
            date: 'October 2024 to Present',
            bullets: [
                'Ongoing project focused on developing learning materials for privacy education',
                'Create of privacy scenarios for educational use',
                'Develop React-based site for interactive learning materials'
            ],
            link:'https://github.com/CtrlPrivacy/Ctrl-Privacy',
            linkText: 'Github Repository'
        },
        {
            title: 'Generating Privacy Stories From Software Documentation',
            date: 'February 2025 to March 2025',
            bullets: [
            'Contributed evaluations of privacy stories that were generated by a large language model',
            "Paper accepted to RENext! '25 at the IEEE International Requirements Engineering 2025 Conference"
            ],
            link:'https://arxiv.org/abs/2506.23014v1',
            linkText: 'View PDF on arXiv '
        }
];

return (
    <div>
      <h1 className="text-2xl font-semibold mb-4 text-center">Research</h1>
      <Card experiences={experiences} />
    </div>
);

}
